import {
  Home,
  CalendarCheck,
  LayoutGrid,
  Trophy,
  History,
  BarChart3,
  LayoutDashboard,
  Swords,
  Medal,
  User,
  PlusCircle,
  Bell,
  Calendar,
  Clock,
  MapPin,
  BadgeCheck,
  Loader2,
  CircleCheck,
  MoreHorizontal,
  ArrowRight,
  ArrowLeft,
  Lock,
  Mail,
  UserPlus,
  ClipboardCheck,
  LogIn,
  LogOut,
  CircleUser,
  Send,
  RotateCcw,
  MailCheck,
  CircleAlert,
  Eye,
  EyeOff,
  Goal,
  Star,
  Zap,
  Menu,
  X,
  ChevronDown,
  ChevronUp,
  Shield,
  ThumbsDown,
  Footprints,
  Egg,
  Turtle,
  Ghost,
  Play,
  Flag,
  BrainCircuit,
  Utensils,
  CircleStar,
  Crown,
  Users,
  type LucideIcon,
} from "lucide-react";

const iconRegistry: Record<string, LucideIcon> = {
  home: Home,
  event_available: CalendarCheck,
  grid_view: LayoutGrid,
  military_tech: Trophy,
  history: History,
  analytics: BarChart3,
  dashboard: LayoutDashboard,
  strategy: Swords,
  leaderboard: Medal,
  person: User,
  add_circle: PlusCircle,
  notifications: Bell,
  calendar_today: Calendar,
  schedule: Clock,
  location_on: MapPin,
  verified: BadgeCheck,
  pending: Loader2,
  check_circle: CircleCheck,
  more_horiz: MoreHorizontal,
  arrow_forward: ArrowRight,
  arrow_back: ArrowLeft,
  lock: Lock,
  mail: Mail,
  person_add: UserPlus,
  how_to_reg: ClipboardCheck,
  login: LogIn,
  logout: LogOut,
  account_circle: CircleUser,
  send: Send,
  lock_reset: RotateCcw,
  mark_email_read: MailCheck,
  error: CircleAlert,
  visibility: Eye,
  visibility_off: EyeOff,
  sports_soccer: Goal,
  star: Star,
  bolt: Zap,
  menu: Menu,
  close: X,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  shield: Shield,
  thumb_down: ThumbsDown,
  footprints: Footprints,
  egg: Egg,
  turtle: Turtle,
  ghost: Ghost,
  play_arrow: Play,
  flag: Flag,
  "brain-circuit": BrainCircuit,
  utensils: Utensils,
  "circle-star": CircleStar,
  crown: Crown,
  group: Users,
};

interface MaterialIconProps {
  name: string;
  className?: string;
}

export function MaterialIcon({ name, className = "" }: Readonly<MaterialIconProps>) {
  const Icon = iconRegistry[name];
  if (!Icon) return null;
  return <Icon className={className} />;
}
